import AppKit
import Observation

/// Something copied: text, or an image with its pasteboard type (PNG or TIFF).
enum ClipboardContent: Equatable, Sendable {
    case text(String)
    case image(Data, type: String)
}

struct ClipboardItem: Identifiable {
    let id = UUID()
    let content: ClipboardContent
    /// A small version of an image, made once when it is copied.
    let thumbnail: NSImage?

    /// Puts `item` on top, dropping an older copy of the same content and the oldest items
    /// beyond `limit`.
    static func inserting(_ item: ClipboardItem, into items: [ClipboardItem], limit: Int) -> [ClipboardItem] {
        Array(([item] + items.filter { $0.content != item.content }).prefix(limit))
    }
}

/// The last texts and images copied anywhere, for the Clipboard tab. Kept in memory only.
/// macOS has no pasteboard change notification, so `changeCount` (a plain integer read) is
/// checked twice a second. Files are left to the shelf, and what password managers mark
/// as concealed or transient is skipped (nspasteboard.org).
@MainActor
@Observable
final class ClipboardHistory {
    private(set) var items: [ClipboardItem] = []
    private(set) var isEnabled = Preferences.clipboardEnabled
    /// The item just copied back, ticked for a moment.
    private(set) var copiedID: UUID?

    @ObservationIgnored private let pasteboard = NSPasteboard.general
    @ObservationIgnored private var timer: Timer?
    @ObservationIgnored private var lastChange = 0
    @ObservationIgnored private var copiedReset: Task<Void, Never>?

    static let limit = 20
    static let maximumTextLength = 200_000
    static let maximumImageBytes = 10_000_000
    static let skippedTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
    ]

    func start() {
        guard isEnabled, timer == nil else { return }
        lastChange = pasteboard.changeCount
        let timer = Timer(timeInterval: 0.5, repeats: true) { [weak self] _ in
            MainActor.assumeIsolated { self?.poll() }
        }
        timer.tolerance = 0.25
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    /// Turning it off also forgets what was copied.
    func setEnabled(_ enabled: Bool) {
        isEnabled = enabled
        Preferences.clipboardEnabled = enabled
        if enabled {
            start()
        } else {
            stop()
            items = []
        }
    }

    /// Puts `item` back on the pasteboard, ready for ⌘V, and moves it to the top.
    func copy(_ item: ClipboardItem) {
        pasteboard.clearContents()
        switch item.content {
        case .text(let text):
            pasteboard.setString(text, forType: .string)
        case .image(let data, let type):
            pasteboard.setData(data, forType: NSPasteboard.PasteboardType(type))
        }
        lastChange = pasteboard.changeCount
        items = ClipboardItem.inserting(item, into: items, limit: Self.limit)
        copiedID = item.id
        Haptics.perform(.action)
        copiedReset?.cancel()
        copiedReset = Task { [weak self] in
            try? await Task.sleep(for: .seconds(1.2))
            guard !Task.isCancelled else { return }
            self?.copiedID = nil
        }
    }

    func remove(_ item: ClipboardItem) {
        items.removeAll { $0.id == item.id }
    }

    func clear() {
        items = []
    }

    private func poll() {
        let change = pasteboard.changeCount
        guard change != lastChange else { return }
        lastChange = change
        guard let item = Self.item(from: pasteboard) else { return }
        items = ClipboardItem.inserting(item, into: items, limit: Self.limit)
    }

    private static func item(from pasteboard: NSPasteboard) -> ClipboardItem? {
        let types = pasteboard.types ?? []
        guard !types.contains(where: { skippedTypes.contains($0.rawValue) }), !types.contains(.fileURL) else {
            return nil
        }
        if let text = pasteboard.string(forType: .string),
           !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty,
           text.count <= maximumTextLength {
            return ClipboardItem(content: .text(text), thumbnail: nil)
        }
        for type in [NSPasteboard.PasteboardType.png, .tiff] {
            guard let data = pasteboard.data(forType: type), data.count <= maximumImageBytes else { continue }
            guard let thumbnail = thumbnail(of: data) else { return nil }
            return ClipboardItem(content: .image(data, type: type.rawValue), thumbnail: thumbnail)
        }
        return nil
    }

    /// Up to 160 pixels on the long side.
    private static func thumbnail(of data: Data) -> NSImage? {
        guard
            let source = CGImageSourceCreateWithData(data as CFData, nil),
            let image = CGImageSourceCreateThumbnailAtIndex(source, 0, [
                kCGImageSourceCreateThumbnailFromImageAlways: true,
                kCGImageSourceThumbnailMaxPixelSize: 160,
                kCGImageSourceCreateThumbnailWithTransform: true,
            ] as CFDictionary)
        else {
            return nil
        }
        return NSImage(cgImage: image, size: .zero)
    }
}
